### ISSUE TITLE
Hardcoded paths in latex.engine

### ISSUE THREAD

**Issue by holms** [martinhewitson/TeXnicle#58]
Is this really right thing to do?

```
ENGINE=/usr/local/bin/latex
DVIPS=/usr/local/bin/dvips
PS2PDF=/usr/local/bin/ps2pdf
```

What do you expect me to install so those binaries would be in there? I'm using macports, and all those binaries are in /opt/local/bin/ directory, and my PATH is correct. Why it's not searching in correct path? Why it's hardcoded? Only developer could fix this.. I gave a task to my poor little girl, to write her first Latex document, and bam, preview doesn't work.. doesn't seems to be legit at all.. I had to changed paths my self  in your software directory.

**Comment by martinhewitson** [comment]
> On 25 Feb 2016, at 16:06, Roman Gorodeckij <notifications@github.com> wrote:
> 
> Is this really right thing to do?
> 
> ENGINE=/usr/local/bin/latex
> DVIPS=/usr/local/bin/dvips
> PS2PDF=/usr/local/bin/ps2pdf
> What do you expect me to install so those binaries would be in there? I'm using macports, and all those binaries are in /opt/local/bin/ directory, and my PATH is correct. Why it's not searching in correct path? Why it's hardcoded? Only developer could fix this.. I gave a task to my poor little girl, to write her first Latex document, and bam, preview doesn't work.. doesn't seems to be legit at all..
> 
> 


You can easily create a new engine which is a copy of the existing engine and then change the paths. All this is explained in the User Manual. TeXnicle is configured to work out of the box with MacTeX. For other LaTeX installations, creating your own engines is quick and easy.

**Comment by holms** [comment]
Ok thanks, haven't noticed anything about MacTex. Been expeting to change certain path in preference :)
